### ISSUE TITLE
Formato

### ISSUE THREAD

**Issue by Rubenmp** [Rubenmp/Ejercicios-Analisis-II#1]
El formato que planteo es el siguiente:

Cada ejercicio debe empezar y terminar con un salto de línea.
Los enunciados de los problemas deben aparecer en negrita
Si un ejercicio no está corregido, poner en el enunciado:
%4. Enunciado

**Comment by josemam** [comment]
Si es posible, molaría poder etiquetar los ejercicios no corregidos con un icono a la izquierda del enunciado. Y marcar también los ejercicios sin terminar (al estilo señal de construcción de los pdfs de Cubero).

Para facilitar la unificación del formato, podríamos hacer un comando que gestione el formato del enunciado de la forma `\enunciado{contenido_del_enunciado}` e incluso otro del tipo `\apartado{enunciado_del_apartado}`.

**Comment by Rubenmp** [comment]
Acabo de poner algo por el estilo, los apartados no se si ponerle algo más
He incluido en el comando \enunciado{...} un \vspace{0.75cm}
